// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/AxialDefault.h"


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driver.reset(new Joystick(0));
    r3.reset(new JoystickButton(driver.get(), 10));
    l3.reset(new JoystickButton(driver.get(), 9));
    start.reset(new JoystickButton(driver.get(), 8));
    back.reset(new JoystickButton(driver.get(), 7));
    rB.reset(new JoystickButton(driver.get(), 6));
    lB.reset(new JoystickButton(driver.get(), 5));
    y.reset(new JoystickButton(driver.get(), 4));
    x.reset(new JoystickButton(driver.get(), 3));
    b.reset(new JoystickButton(driver.get(), 2));
    a.reset(new JoystickButton(driver.get(), 1));

    // SmartDashboard Buttons
    SmartDashboard::PutData("AxialDefault", new AxialDefault());
    SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<Joystick> OI::getDriver() {
   return driver;
}


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
