// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#ifndef OI_H
#define OI_H

#include "WPILib.h"

class OI {
private:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	std::shared_ptr<Joystick> driver;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
public:
	OI();

	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES

	std::shared_ptr<Joystick> getDriver();
	std::shared_ptr<JoystickButton> r3;
	std::shared_ptr<JoystickButton> l3;
	std::shared_ptr<JoystickButton> start;
	std::shared_ptr<JoystickButton> back;
	std::shared_ptr<JoystickButton> rB;
	std::shared_ptr<JoystickButton> lB;
	std::shared_ptr<JoystickButton> y;
	std::shared_ptr<JoystickButton> x;
	std::shared_ptr<JoystickButton> b;
	std::shared_ptr<JoystickButton> a;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PROTOTYPES
};

#endif
